name: ci-js-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm run test
      - run: node index.js
