name: ci-js-workflow
on: [push]
jobs:
  check-applications:
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v2
      - uses: setup-node
        with:
          node-version: 14
      - run: npm run test
      - run: node index.js
